FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

ARG BUILDCONFIG=RELEASE
ARG VERSION=1.0.0

COPY ContainersApp.csproj /build/

RUN dotnet restore ./build/ContainersApp.csproj

COPY . ./build/
WORKDIR /build/
RUN dotnet publish ./ContainersApp.csproj -c $BUILDCONFIG -o out /p:Version=$VERSION

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0.0
WORKDIR /app
COPY --from=build /build/out .
ENTRYPOINT ["dotnet", "ContainersApp.dll"]