resource_group_name         = "rgContainersAz204"
resource_group_location     = "West Europe"
virtual_network_name        = "vnet204"
subnet_name                 = "subnet019"
public_ip_name              = "publici204"
network_security_group_name = "nsgprod204"
network_interface_name      = "nicprod204"
linux_virtual_machine_name  = "rgContainersLinuxvmaz204"