apiVersion: 2019-12-01
location: northeurope
name: SQLAppGroup2
properties:
  containers: 
  - name: db
    properties:
      image: containerregistrysqliaz204.azurecr.io/appsqlimage:tagone
      resources:
        requests:
          cpu: 1
          memoryInGb: 1.5
      ports:
      - port: 3306
  - name: web
    properties:
      image: containerregistrysqliaz204.azurecr.io/containers-app:latest
      resources:
        requests:
          cpu: 1
          memoryInGb: 1.5
      ports:
      - port: 80          
  osType: Linux
  ipAddress:
    type: Public
    ports:
    - protocol: tcp
      port: 80
  imageRegistryCredentials:
    - server: containerregistrysqliaz204.azurecr.io
      username: containerRegistrysqliaz204
      password: bNYj+aMjp6ys5e1URIgsfbt3wM+G+85Ky96HlRQmOx+ACRCYYp/Y
type: Microsoft.ContainerInstance/containerGroups